### ISSUE TITLE
Issue while Configuring XDC Subnet on Testnet (XDC Apothem Network)

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XDC-Subnet#129]
Hello @wanwiset25,

I attempted to set up a subnet on the Testnet (XDC Apothem network) following the updated document at "https://xinfinorg.github.io/xdc-subnet-docs/deployment/launch_subnet/". I modified "PARENTNET" to "testnet" as instructed.

However, when deploying the "checkpoint smart contract," I encountered the error "Error: deploy to parentnet node failure, pls check the parentnet node status."

Could you please investigate this issue? Your assistance is highly appreciated.

![GithubSubnetIssueTestnet](https://github.com/XinFinOrg/XDC-Subnet/assets/39384359/80681518-e720-4509-ad72-ff3df15d15da)

**Comment by wanwiset25** [comment]
Hi @vrushalipanchal 
It seems there is some issue with the default generated testnet URL. Further checking the URL is not in our control. In the next version we will deploy new testnet RPC node and switch the default testnet URL. Meanwhile devnet is back online so you can use with PARENTNET=devnet for testing.

**Comment by vrushalipanchal** [comment]
For now, Can we change RPC URL? Please, Let me know how to change it ?

**Comment by wanwiset25** [comment]
To specify RPC_URL change the config `PARENTNET_URL` in common.env. These urls should be working now (devnet, testnet)
https://devnetstats.apothem.network/devnet
https://devnetstats.apothem.network/testnet

**Comment by vrushalipanchal** [comment]
As per the suggestions, I have set up the subnet on the Testnet (XDC Apothem network). However, on the frontend side, the "Checkpointed to" is displaying "Devnet" instead of "Testnet."

![image](https://github.com/XinFinOrg/XDC-Subnet/assets/39384359/6e2e5684-a2cf-466b-b38c-be80b0e8ab97)

Please look into this. 

Thank you!

**Comment by wanwiset25** [comment]
Hi 
I've checked and this is a frontend bug, will look to fix in the next version.
