### ISSUE TITLE
Update subnet block confirmation rule at the parent chain

### ISSUE THREAD

**Issue by fishermanymc** [XinFinOrg/XDC-Subnet#54]
Suppose subnet block S-50 is confirmed by subnet block S-55.
Suppose S-50 is checkpointed to parent chain block P-100, and S-55 is checkpointed to P-102.
Then, S-50 is confirmed that the parent chain if:

- all subnet block headers up to S-55 have been submitted to the checkpoint smart contract
   (which confirms S-50 inside the checkpoint smart contract)
- P-102 has been confirmed in the parent chain
   (so that S-55 will not have any competitor).

Thus,
- when the checkpoint smart contract receives S-50, it should create a mapping between S-50 and an empty int as block height
- when the checkpoint smart contract receives S-55, and once S-55 confirms S-50, the value of the empty int for S-50 should be updated to 102
- when a client queries the checkpoint smart contract about the status of S-50, among other things, the smart contract must return this int.  If `nil`, the checkpoint smart contract has not confirmed S-50 yet. If 102, the client should continue to query the parent chain node whether P-102 has been confirmed or not. If yes, then S-50 is confirmed by the parent chain.

**Comment by GalaxySciTech** [comment]
https://github.com/XinFinOrg/XDC-Subnet/pull/55

The pr will update it
