### ISSUE TITLE
ERROR:-could not detect the network.

### ISSUE THREAD

**Issue by Mitali-88** [XinFinOrg/XDC-Subnet#88]
I am encountering an issue while configuring my custom subnet. When I execute the "deploy checkpoint smart contract" command as specified in the commands.txt file, I receive an error message.

I've come across a configuration issue with my XDC subnet. Following the instructions in the commands.txt file, when I attempt to execute the 'deploy checkpoint smart contract' command, I encounter an error message stating 'could not detect the network.'

Please refer below screenshot:
![VirtualBox_ubuntu18_03_09_2023_22_30_01](https://github.com/XinFinOrg/XDC-Subnet/assets/71551940/089973d8-337b-4c1d-ade7-61ad2655ee98)
I followed the same steps mentioned in these articles.

https://xinfinorg.github.io/xdc-subnet-docs/deployment/launch_subnet/

https://www.xdc.dev/vinn_9686/xdc-subnet-installation-guide-building-a-secure-and-scalable-network-4hb3

**Comment by wanwiset25** [comment]
Hi @Mitali-88 
Are you still facing this issue? There was downtime on the devnet endpoint over the weekend. 
Please share your 'deployment.json' file if the CSC deployment still isn't working.

**Comment by wanwiset25** [comment]
Hi @Mitali-88
If no further inquiry on this, I will close the issue in 3 days.

**Comment by Mitali-88** [comment]
Yes Thank you @wanwiset25 the issue is resolved, i have successfully setup my subnet
you can close this

**Comment by wanwiset25** [comment]
@Mitali-88 
Great to know that, thank you!
