### ISSUE TITLE
The "Relayer Info" of Subnet status was "Abnormal"

### ISSUE THREAD

**Issue by vrushalipanchal** [XinFinOrg/XDC-Subnet#92]
Hello @wanwiset25 

For some time, the status of my subnet, as indicated in the attached screenshot, was **"Abnormal."** During this period, the balance in my wallet was less than 1 XDC.

![image](https://github.com/XinFinOrg/XDC-Subnet/assets/39384359/a0827752-645f-4033-a880-88a88986c973)

Subsequently, I added funds to my account, and the current status of "Relayer Info" is now "Normal."

I am uncertain whether the issue was related to the insufficient funds in the account or if there was another underlying problem.

Please provide clarification on this matter. If the issue was indeed related to the fund balance, kindly specify the required minimum fund amount to successfully run the subnet. Additionally, it would be helpful to know if there are plans to implement notifications for "No funds in the account" in the future. Your guidance is greatly appreciated.

**Comment by wanwiset25** [comment]
The relayer status works by checking the time of last submitted block on the Parentchain Checkpoint Smart Contract. The status will show as 'Abnormal' if the time of last submission is more than 1000 seconds. Meaning for whichever reason, new blocks are unable to be pushed on to the smart contract.

So, yes, this is related to the relayer account's funding issue. And thanks for your suggestion on the 'No funds' warning.
